import { Router } from "express";
import healthRouter from "./health";
import meRouter from "./me";
import tasksRouter from "./tasks";
import sectorsRouter from "./sectors";
import projectsRouter from "./projects";
import goalsRouter from "./goals";
import milestonesRouter from "./milestones";
import statsRouter from "./stats";
import listsRouter from "./lists";
import financesRouter from "./finances";
import workoutRouter from "./workout";
import dreamBoardRouter from "./dream-board";
import documentsRouter from "./documents";
import commentsRouter from "./comments";
import attachmentsRouter from "./attachments";
import feedbackRouter from "./feedback";
import streakRouter from "./streak";
import membersRouter from "./members";
import productivityProfileRouter from "./productivity-profile";

const router = Router();

router.use("/healthz", healthRouter);
router.use("/me", meRouter);
router.use("/tasks", tasksRouter);
router.use("/sectors", sectorsRouter);
router.use("/projects", projectsRouter);
router.use("/goals", goalsRouter);
router.use("/milestones", milestonesRouter);
router.use("/stats", statsRouter);
router.use("/lists", listsRouter);
router.use("/finances", financesRouter);
router.use("/workout", workoutRouter);
router.use("/dream-board", dreamBoardRouter);
router.use("/documents", documentsRouter);
router.use("/comments", commentsRouter);
router.use("/attachments", attachmentsRouter);
router.use("/feedback", feedbackRouter);
router.use("/streak", streakRouter);
router.use("/members", membersRouter);
router.use("/productivity-profile", productivityProfileRouter);

export default router;
